name: run

on:
  schedule:
    - cron: '00 16 * * *'
  watch:
    types: started
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 安装环境并获取环境变量
        env:
          USER: ${{ secrets.USER }}
          PASSWORD: ${{ secrets.PASSWORD }}
          PUSH_MESSAGE: ${{ secrets.PUSH_MESSAGE }}
        run: |
          pip install --upgrade pip
          pip install requests
          pip install selenium
      - name: 运行脚本
        run: python3 /home/runner/work/Sign-WenShuShu/Sign_WenShuShu_selenium.py
